CODEOWNERS

The CODEOWNERS file had users not really active in upstream so remove them.

[noup] CODEOWNERS: fix the list of users

---

src/utils/common.h

Fix build error that IFNAMSIZ redefined in zephyr and unknown type name 'sa_family_t', and fix the build warning of 'struct in_addr' declared inside parameter list will not be visible outside of this definition or declaration.

[toup] zephyr: Fix build error and warning of zephyr

---

port/mbedtls/supp_psa_api.c
port/mbedtls/supp_psa_api.h
port/mbedtls/wpa_supp_els_pkc_mbedtls_config.h
src/common/dpp.c
src/common/dpp_auth.c
src/crypto/crypto_mbedtls_alt.c
src/crypto/tls_mbedtls_alt.c

Port crypto mbedtls wrapper for enterprise and DPP.
Porting from
https://github.com/gstrauss/hostap/blob/mbedtls/src/crypto/crypto_mbedtls.c

[toup] zephyr: crypto: port crypto mbedtls wrapper

---

wpa_supplicant/wpa_cli_zephyr.c

wpa_cli command with interactive means to show response info on console.
In this case it is better to use MSG_INFO level to print instead of
MSG_DEBUG level. As MSG_DEBUG level is for debug cases, but wpa_cli
response print is normal use case.

[noup] zephyr: use MSG_INFO level for wpa_cli command response print

---

src/utils/os_zephyr.c

When compiling zephyr with the test random generator, sys_csrand_get() is not available. Allow fallback to sys_rand_get() if no entropy driver exists.
Without this patch, it is not possible to build the nrf70 WiFi device driver as it depends on WPA_SUPPLICANT, which depends on `sys_csrand_get()` for boards without hardware RNG.
```
/home/nordic/Documents/zephyr-sdk/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/hostap/libmodules__hostap.a(os_zephyr.c.obj): in function `sys_csrand_get':
/home/nordic/Documents/zephyr-1/build/zephyr/include/generated/zephyr/syscalls/random.h:61: undefined reference to `z_impl_sys_csrand_get'
collect2: error: ld returned 1 exit status
```

[noup] utils: os_zephyr: Fall back to sys_rand if no csrand

---

src/drivers/driver_zephyr.c
wpa_supplicant/ctrl_iface_zephyr.c
wpa_supplicant/wpa_cli_zephyr.c

1. when enable hostapd, print Interface initialization failed log.
wpa_init_keys will check the netif running status when setup bss but fail.
use net_if_is_admin_up to check interface up status.
2. change "CTRL_MSG too long" to debug log level to avoid misunderstanding in normal case.

[noup]: hostap: fix start ap fail

---

src/drivers/driver_zephyr.c

Fix memory leak in wpa_supplicant_event_wrapper().

[nxp noup] zephyr: Fix memory leak in supplicant

---

src/common/sae.c

For low-performance processors, reduce the number of loop iterations for PWE derivation to reduce the time to generate PWE. Add CONFIG_SAE_PWE_EARLY_EXIT macro to enable it.

[noup] SAE: reduce loop iterations of PWE derivation

---

src/drivers/driver_zephyr.c
src/drivers/driver_zephyr.h
wpa_supplicant/eap_register.c

In SAP mode, need to fetch the inactivity timer value for a STA from the UMAC.

[nrf noup] zephyr: Add support for fetching inactivity timer

---

src/crypto/tls_mbedtls_alt.c

Enable TLS_MBEDTLS_CERT_VERIFY_EXTMATCH, to support the domain_match check, which is needed for the WPA3 CERT 11.1 case.

[toup] crypto: enable TLS_MBEDTLS_CERT_VERIFY_EXTMATCH

---

src/utils/os.h

When build the Matter over Wi-Fi with NEWLIB enabled, there is build error shows 'error: unknown type name 'FILE' ', adding this change can fix this build error, and don't affect the case that NEWLIB disabled.

[toup] zephyr: fix the build error that unknown FILE

---

src/crypto/tls_mbedtls_alt.c

For EAP-TLS, secret key len is always 48, and MD_SIZE is 32, this causes authentication failure.

[nrf noup] crypto_alt: Fix secret key len

---

port/mbedtls/supp_psa_api.c
port/mbedtls/supp_psa_api.h
src/crypto/crypto_mbedtls_alt.c

Add PSA API based pbkdf2 wrapper. This wrapper implements pbkdf2 algorithm using only PSA APIs. The PSA API based wrapper is tested for the test vectors defined in J.4.2 in 802.11-2020 and also verified via connection.

[toup] zephyr: crypto: Add SHA1 PBKDF2 using PSA APIs

---

src/drivers/driver_zephyr.c

Fix build error when CONFIG_WIFI_NM_HOSTAPD_AP is enabled, should use the new API net_if_get_wifi_sap().

[noup] zephyr: Fix build error when hostapd enabled

---

hostapd/hostapd_cli_cmds.c
hostapd/hostapd_cli_zephyr.c
hostapd/hostapd_cli_zephyr.h
src/ap/hostapd.h
src/drivers/driver_zephyr.c
src/drivers/driver_zephyr.h
wpa_supplicant/ctrl_iface_zephyr.c
wpa_supplicant/wpa_cli_zephyr.c
wpa_supplicant/wpa_supplicant_i.h

510c2609a8b62acdcd1deaa4e2a9c20bb303f234
[noup] zephyr: fix hostapd_cli set command parse wrong in zephyr
hostapd_config_parse_key_mgmt can parse more than two argcs.
And hostapd_cli shell command has one more "interactive" argv,
which makes argc not equal to 2.
So align with wpa_cli_cmd_set.
a41113eb54fc208b0e22368b9891e13cdba83540
[noup] add hostapd_cli shell support
Add hostapd_cli shell command.
Porting from zephyr wpa_cli impl.
83d7a2b827515e9c3142fdc629679fb317286be4
[noup] fix hostapd ctrl msg receive build error
Fix build error that 'len' is undefined in hostapd_cli_recv_pending.
960516c8e32a662b73b9aac012d82cc814aa71c4
[noup] hostapd: add dispatch for hostapd and wpa_supplicant wpa_msg
When we have coexistence of hostapd and wpa_supplicant,
wpa_msg has different implementation …

DPP bug fixes

---

src/drivers/driver_zephyr.c
src/drivers/driver_zephyr.h

If AP starts on DFS channel, hostapd will wait for CAC start and finish event. Added CAC callback functions in Zephyr driver.

[noup] zephyr: Add CAC support if AP started on DFS channel

---

src/crypto/tls_mbedtls_alt.c

If the incoming cert is not a PEM then the length is incremented to handle null byte, but null byte itself is not added, this causes MbedTLS to parse the extra byte and causing UNKNOWN_TAG parser error depending on the value at that byte.
In case the user doesn't give PEM then let MbedTLS handle parsing and failing appropriately. MbedTLS has much stricter PEM format checks than this file.

[noup] Fix incorrect length increment

---

hostapd/sae_pk_gen.c
hs20/client/est.c
hs20/client/osu_client.c
hs20/server/spp_server.c
src/common/dpp.c
src/common/dpp_crypto.c
src/common/sae_pk.c
src/eap_peer/tncc.c
src/eap_server/tncs.c
src/tls/tlsv1_cred.c
src/utils/base64.c
src/utils/base64.h
src/utils/json.c
src/utils/utils_module_tests.c
src/utils/xml_libxml2.c
src/wps/upnp_xml.c
src/wps/wps_er.c
src/wps/wps_registrar.c
src/wps/wps_upnp.c
src/wps/wps_upnp_web.c
tests/hwsim/test_ap_wps.py
tests/hwsim/test_tnc.py
tests/test-base64.c
wpa_supplicant/config_file.c
wpa_supplicant/dpp_supplicant.c
wpa_supplicant/eapol_test.c
wpa_supplicant/hs20_supplicant.c

Zephyr provides own base64 library with the same function names as hostap. Because of this, it's not possible to build applications enabling both supplicant and CONFIG_BASE64. As Zephyr takes preference here, we need to rename the colliding functions in hostap.

[noup] base64: Rename base64_encode/decode functions

---

src/drivers/driver_zephyr.c

When allocating hostapd_hw_modes->channels memory, phy_info_freqs_cfg() does not clean up the memory and use the tx_power in hw_feature_data. So, the maximum transmit power level in the country IE is a garbage value, and the 2G channel cannot form a sub-band.

[toup] zephyr: Fixed the max tx power level in Country IE being garbag

---

wpa_supplicant/wpa_cli_zephyr.c

The event value should be of type "enum net_event_wifi_cmd" so use a value from that range.

zephyr: Use proper event value when sending supplicant event

---

port/mbedtls/supp_psa_api.c

Add crypto module test under macro
CONFIG_WIFI_NM_WPA_SUPPLICANT_CRYPTO_TEST,
so that developer can enable it for crypto debug test.

[noup] zephyr: mbedtls: add crypto module test

---

src/utils/os.h
src/utils/os_zephyr.c
wpa_supplicant/ctrl_iface.c
wpa_supplicant/events.c
wpa_supplicant/wnm_sta.c
wpa_supplicant/wpa_supplicant.c

Hostap define os_time_t as long but zephyr add own definition to long long and change hostap original code to fix warnings. Thus when DPP enabled, unfixed warning will pop out. We do not want to change so many original hostap code. So it is better to remain original os_time_t definition as long. Fix it by revert os_time_t own definition for zephyr and related printf format change also.
And fix coverity issue by converting time to os_time_t in os_get_time.

[noup] zephyr: revert zephyr change for os_time_t to origin

---

src/ap/hostapd.c

When AP is enabled using WPA supplicant we get two AP enable events, one from WPA supplicant and other from hostapd.
FYI @nxf58150

[no up] ap: Fix double event sending

---

src/utils/common.h

Fix build error of undefined reference to 'inet_aton' in hostap/src/utils/ip_addr.c

[toup] zephyr: fix build error of inet_aton

---

src/crypto/tls_mbedtls_alt.c

For some certificate files may check key usage fail and send alert message to AP.
Enable TLS_MBEDTLS_CERT_DISABLE_KEY_USAGE_CHECK to disable key usage check.

zephyr: cert: fix check AP certificate file fail

---

src/crypto/tls_mbedtls_alt.c

Remove the include of fsl_debug_console.h, which is not used for Zephyr

[toup] crypto: remove the include of fsl_debug_console.h

---

src/common/wpa_ctrl.c

WPA control interface timeout is hardcoded to 10s, use the newly introduced configuration option, this is needed sometimes as a workaround e.g., crypto taking too long to complete the request.
Work around for #79834.
Note: Though a generic change, this is marked as `noup` because typically 10s timeout is plenty and I don't think an extra config option would be welcomed :).

[noup] wpa_ctrl: Add a config option for WPA control timeout

---

src/drivers/driver_zephyr.c
src/drivers/driver_zephyr.h
wpa_supplicant/ctrl_iface.c
wpa_supplicant/wpa_cli_zephyr.c

Added roaming support in wpa_supplicant for Zephyr.

zephyr: Roaming support

---

src/ap/drv_callbacks.c
src/ap/hostapd.c
src/ap/hw_features.c
src/ap/hw_features.h

Warning prints "<wrn> wpa_supp: Failed to check if DFS is required; ret=-1" are seen during SAP switch to 2.4G's channel using ECSA CMD when SAP started on 5G channels first. The root cause is that when SAP switch to 2.4G, its iface->current_mode is still about 5G, not updated. Check the upstream hostap code, there is already related fix, so porting it here.
fix: https://github.com/zephyrproject-rtos/zephyr/issues/81123

Fix ECSA warning log and current_mode is not correct.

---

wpa_supplicant/wpa_cli_zephyr.c
wpa_supplicant/wpa_cli_zephyr.h

This is needed for Matter applications as specific by the Spec, it just says PHY rate, but Linux and other implementations only use TX rate.

[noup] zephyr: Add support for fetch current TX rate

---

src/ap/ap_config.h
src/ap/authsrv.c

As we do not have file system support, add cert blob element
to allow parse cert data by blob instead of file for SAP.

zephyr: cert: Add blob element to support parse cert data by blob

---

src/crypto/tls_mbedtls_alt.c

Fix for WPA3 enterprise suiteb192 rsa3k connect fail.
Let default config not use MBEDTLS_SSL_PRESET_SUITEB as input mbedtls_ssl_config_defaults().
For rsa3k case has TLS_CONN_SUITEB flag and will
choose MBEDTLS_SSL_PRESET_SUITEB as input.
Then the signature algorithm will set to
ssl_tls12_preset_suiteb_sig_algs which removed rsa. Then will cause EAP Hello packet not include rsa in sig_alg and AP will return EAP failure.
Use MBEDTLS_SSL_PRESET_DEFAULT as input.

[toup] mbedtls: Fix for WPA3 enterprise suiteb192 rsa3k

---

hostapd/hostapd_cli_zephyr.c

print too long msg when eap enterprise.
we should not print the log, so set print type to debug.

zephyr: modify log type from info to debug

---

src/drivers/driver_zephyr.c

If the WiFi device driver does not support the supplicant API, check for a null pointer before calling the init function.
Fixes #82938

wifi: hostap: Check dev_ops pointer before using

---

src/drivers/driver_zephyr.c
src/drivers/driver_zephyr.h

zperf udp tx throughput uses fixed ip address, if run legacy roaming at
this time, roaming will restart dhcp and ip address is changed,
so zperf can't find ip address when zperf send udp packet during legacy
roaming, and zperf udp tx fail.
we think that legacy roaming shouldn't restart dhcp, so we need to
determine whether current connection is a normal connection or a
roaming, and determine whether we should restart dhcp.
and we use assoc_freq parameter in wps_supplicant to get current connect
state.
if assoc_freq is not 0, it indicates that the sta already connects, and
current connection is roaming, so we doesn't start dhcp.
if assoc_freq is 0, it indicates that current connection is a normal
connection rather than roaming, so we want to start dhcp.

zephyr: udp throughput fail when legacy roaming

---

src/crypto/crypto_mbedtls_alt.c

When WPA3 is not enabled, EC is disabled and if ECDH is enabled (by Wi-Fi or non-Wi-Fi like TLS) then this would cause a build warning and twister fails.

[noup] zephyr: Fix unused function warning

---

zephyr/module.yml

Add CPE and PURL references to module.yml for for use by Zephyr's SPDX generation tool.
See github issue in Zephyr repo: https://github.com/zephyrproject-rtos/zephyr/issues/53479
I *think* the PURL is about right based on the "generic" examples in here: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst but happy to update if there are any better suggestions.

module: add security info to module.yml

---

src/crypto/crypto_mbedtls_alt.c
src/crypto/tls_mbedtls_alt.c

The static initialization of hostap_rng_ctx results in passing a NULL context pointer which results in a crash. Initialize rng context before passing it to MPI calls.

[noup] zephyr: Fix WPA3 connection issue

---

src/l2_packet/l2_packet_zephyr.c

Due to a recent change the Zephyr network stack sends the protocol in network byte order, so, need to be converted to host order before using it. This was dropping all EAPoL frames and broke secure association.

[noup] zephyr: Fix the Wi-Fi secure associations

---

hostapd/hostapd_cli_zephyr.c
src/ap/hostapd.c
src/ap/hw_features.c
src/ap/sta_info.c

Update SoftAP event functions of Zephyr with hostapd enabled.

zephyr: Update SoftAP event functions of Zephyr with hostapd enabled

---

src/crypto/crypto_mbedtls_alt.c

Fix DPP3 build error for latest upmerge.
Porting from original file to fix missing api build error, https://github.com/gstrauss/hostap/blob/mbedtls/src/crypto/crypto_mbedtls.c.

zephyr: crypto: fix DPP3 build error

---

src/ap/hostapd.c

commit f72b2d440 removed the guard causing build issues when AP is enabled using wpa_supplicant.

[noup] zephyr: Fix build error

---

src/crypto/tls_mbedtls_alt.c

MbedTLS new release notes for 3.6.3 [1] now mandates that hostname verification is enabled, so, disable it explicitly till a proper hostname configuration is implemented.
[1] - https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.3

[noup] zephyr: mbedtls: Fix certificate verification failure

---

src/common/wpa_ctrl.c
wpa_supplicant/wpa_cli_zephyr.c

During the monitor socket rework, these are removed from the control interface but were left over in wpa_cli this causes an error message during interface down.

[noup] zephyr: Remove non-existent attach/detach helper

---

src/utils/os_zephyr.c

Create dedicated heap for supplicant operations. Currently, WPA supplicant uses the k_malloc, which is shared across various subsystems, and we cannot enforce a minimum availability. Using a dedicated HEAP that can be pre-allocated solves this by always having necessary memory.

[noup] zephyr: Create dedicated heap for supplicant

---

wpa_supplicant/ctrl_iface_zephyr.h

Fix header include path for eloop.h when
including ctrl_iface_zephyr.h from another module.

[noup] zephyr: Fix header file path

---

src/drivers/driver.h
wpa_supplicant/events.c
wpa_supplicant/wpa_supplicant.c
wpa_supplicant/wpa_supplicant_i.h

Some drivers take longer than 100ms, and there by the keepalive is sent after the keepalive period and this causes disconnections sometimes, so, adjust for the driver's processing delay (a new driver capability) and send the keepalive early (no harm in sending early).
Upstream PR: https://lists.infradead.org/pipermail/hostap/2025-July/043623.html

[fromlist] SME: Add configurable driver processing time

---

wpa_supplicant/wpa_supplicant.c

An argument was missing to call wpa_supplicant_get_scan_results, fix this and fix an alignment for another call.
Original commit message from 5b4a78b1f90977fdd013baffa0a05c47ef59f817:
```
Optimize internal BSS table updates based on a specific BSSID
When wpa_supplicant needed to update the internal BSS table with the
latest scan results from the driver, it fetched all BSSs and processed
them all. This is unnecessary for cases where an update is needed only
for a specific BSS. Optimize this by filtering out the unnecessary
entries from the results.
```

[noup] Fix fromtree cherry-picked for wpa_supplicant_get_scan_results
